source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'ios-accordion', :exclusive => true do
  pod "ios-accordion", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ios-accordion", :path => "../"

  
end
