source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod "ALAccordion", :path => "../"

target 'ALAccordion Example' do

end

target 'ALAccordion Tests' do
  pod 'Quick', '~> 0.3.1'
  pod 'Nimble', '~> 0.4.2'
end
