source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

pod "ALAccordion", :path => "../"

target 'ALAccordion Example' do

end

target 'ALAccordion Tests' do
  pod 'Quick', :git => 'https://github.com/Quick/Quick', :branch => 'swift-2.0'
  pod 'Nimble', '~> 2.0.0-rc.3'
end
